# Generated by Django 5.1 on 2025-11-19 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_a', models.CharField(help_text='模型A的名称', max_length=100)),
                ('model_b', models.CharField(help_text='模型B的名称', max_length=100)),
                ('prompt', models.TextField(help_text='用户输入的提示')),
                ('winner', models.CharField(help_text="获胜方的名称, 'tie', 或 'both_bad'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, help_text='对话使用的模型名称', max_length=100, null=True)),
                ('mode', models.CharField(choices=[('direct-chat', 'Direct Chat'), ('side-by-side', 'Side by Side'), ('battle', 'Battle')], default='direct-chat', help_text='对话模式', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=10)),
                ('content', models.TextField()),
                ('is_user', models.BooleanField(default=True, help_text='True表示用户消息，False表示AI回复')),
                ('model_name', models.CharField(blank=True, help_text='生成此消息的模型名称（仅AI消息）', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='models_manager.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
