# Generated by Django 5.1 on 2025-11-07 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_a', models.CharField(help_text='模型A的名称', max_length=100)),
                ('model_b', models.CharField(help_text='模型B的名称', max_length=100)),
                ('prompt', models.TextField(help_text='用户输入的提示')),
                ('winner', models.CharField(help_text="获胜方的名称, 'tie', 或 'both_bad'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
