# Generated by Django 5.1 on 2025-12-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_a', models.CharField(help_text='模型A的名称', max_length=100)),
                ('model_b', models.CharField(help_text='模型B的名称', max_length=100)),
                ('prompt', models.TextField(help_text='用户输入的提示')),
                ('winner', models.CharField(help_text="获胜方的名称, 'tie', 或 'both_bad'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0, help_text='综合总分')),
                ('scores', models.JSONField(default=dict, help_text="分类得分，如 {'代码能力': 95.0}")),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_score', to='models_manager.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model_name', models.CharField(blank=True, help_text='对话使用的模型名称', max_length=100, null=True)),
                ('mode', models.CharField(choices=[('direct-chat', 'Direct Chat'), ('side-by-side', 'Side by Side'), ('battle', 'Battle')], default='direct-chat', help_text='对话模式', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='models_manager.chatconversation')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=10)),
                ('content', models.TextField()),
                ('is_user', models.BooleanField(default=True, help_text='True表示用户消息，False表示AI回复')),
                ('model_name', models.CharField(blank=True, help_text='生成此消息的模型名称（仅AI消息）', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_evaluations', to=settings.AUTH_USER_MODEL)),
                ('dataset_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('evaluation_mode', models.CharField(default='unknown', max_length=64)),
                ('benchmark_type', models.CharField(blank=True, max_length=128)),
                ('total_prompts', models.IntegerField(default=0)),
                ('evaluated_prompts', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_samples', models.JSONField(blank=True, default=list)),
                ('elapsed_seconds', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetEvaluationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='models_manager.datasetevaluationresult')),
                ('index', models.IntegerField()),
                ('prompt', models.TextField(blank=True)),
                ('expected_answer', models.TextField(blank=True)),
                ('model_response', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('included_in_metrics', models.BooleanField(default=True)),
                ('skipped', models.BooleanField(default=False)),
                ('sample_time', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, help_text='快照时间')),
                ('leaderboard_data', models.JSONField(default=list, help_text='排行榜完整数据（JSON数组）')),
                ('total_models', models.IntegerField(help_text='参与排名的模型数量')),
                ('total_battles', models.IntegerField(help_text='总对战次数')),
            ],
            options={
                'verbose_name': '排行榜快照',
                'verbose_name_plural': '排行榜快照',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ModelTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('accuracy', '准确度'), ('latency', '响应延迟'), ('throughput', '吞吐量'), ('perplexity', '困惑度'), ('custom', '自定义')], default='custom', help_text='测试类型', max_length=50)),
                ('test_name', models.CharField(help_text='测试名称', max_length=255)),
                ('description', models.TextField(blank=True, help_text='测试描述')),
                ('test_data', models.JSONField(blank=True, default=dict, help_text='测试数据集')),
                ('score', models.FloatField(help_text='测试得分/结果')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='详细指标')),
                ('status', models.CharField(choices=[('pending', '待测试'), ('running', '测试中'), ('passed', '通过'), ('failed', '失败')], default='pending', help_text='测试状态', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='测试执行者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(help_text='测试的模型', on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='models_manager.aimodel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模型名称', max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='展示名称', max_length=200)),
                ('owner', models.CharField(blank=True, help_text='模型所有者/提供商', max_length=100)),
                ('description', models.TextField(blank=True, help_text='模型描述')),
                ('elo_rating', models.FloatField(default=1500.0, help_text='ELO评分，初始值1500')),
                ('total_battles', models.IntegerField(default=0, help_text='总对战次数')),
                ('wins', models.IntegerField(default=0, help_text='胜利次数')),
                ('losses', models.IntegerField(default=0, help_text='失败次数')),
                ('ties', models.IntegerField(default=0, help_text='平局次数')),
                ('task_type', models.CharField(blank=True, help_text='任务类型（如：通用、代码、翻译等）', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='是否在排行榜中显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-elo_rating'],
                'indexes': [models.Index(fields=['-elo_rating'], name='models_mana_elo_rat_c97aa7_idx')],
            },
        ),
    ]
