# Generated by Django 5.1 on 2025-12-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 已合并到 0001_initial.py 中，避免重复添加列。此迁移保持为空以兼容历史记录。
    operations = []
