# Generated by Django 5.1 on 2025-12-05 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battlevote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='models_manager.chatconversation'),
        ),
        migrations.AddField(
            model_name='datasetevaluationresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetevaluationsample',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='models_manager.datasetevaluationresult'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationresult',
            index=models.Index(fields=['dataset_name'], name='models_mana_dataset_19c134_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationresult',
            index=models.Index(fields=['model_name'], name='models_mana_model_n_cb8807_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationresult',
            index=models.Index(fields=['status'], name='models_mana_status_b0efe8_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationresult',
            index=models.Index(fields=['created_at'], name='models_mana_created_308545_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationsample',
            index=models.Index(fields=['result', 'index'], name='models_mana_result__fed9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationsample',
            index=models.Index(fields=['result', 'is_correct'], name='models_mana_result__be2847_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationsample',
            index=models.Index(fields=['result', 'skipped'], name='models_mana_result__d52871_idx'),
        ),
    ]
