# Generated by Django 5.1 on 2025-12-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0002_aimodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, help_text='快照时间')),
                ('leaderboard_data', models.JSONField(default=list, help_text='排行榜完整数据（JSON数组）')),
                ('total_models', models.IntegerField(help_text='参与排名的模型数量')),
                ('total_battles', models.IntegerField(help_text='总对战次数')),
            ],
            options={
                'verbose_name': '排行榜快照',
                'verbose_name_plural': '排行榜快照',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ModelTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('accuracy', '准确度'), ('latency', '响应延迟'), ('throughput', '吞吐量'), ('perplexity', '困惑度'), ('custom', '自定义')], default='custom', help_text='测试类型', max_length=50)),
                ('test_name', models.CharField(help_text='测试名称', max_length=255)),
                ('description', models.TextField(blank=True, help_text='测试描述')),
                ('test_data', models.JSONField(blank=True, default=dict, help_text='测试数据集')),
                ('score', models.FloatField(help_text='测试得分/结果')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='详细指标')),
                ('status', models.CharField(choices=[('pending', '待测试'), ('running', '测试中'), ('passed', '通过'), ('failed', '失败')], default='pending', help_text='测试状态', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='测试执行者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(help_text='测试的模型', on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='models_manager.aimodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model', '-created_at'], name='models_mana_model_i_8af38e_idx'), models.Index(fields=['test_type', '-created_at'], name='models_mana_test_ty_e6edd4_idx')],
            },
        ),
    ]
