# Generated by Django 5.1 on 2025-12-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('evaluation_mode', models.CharField(default='unknown', max_length=64)),
                ('benchmark_type', models.CharField(blank=True, max_length=128)),
                ('total_prompts', models.IntegerField(default=0)),
                ('evaluated_prompts', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_samples', models.JSONField(blank=True, default=list)),
                ('elapsed_seconds', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetEvaluationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('prompt', models.TextField(blank=True)),
                ('expected_answer', models.TextField(blank=True)),
                ('model_response', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('included_in_metrics', models.BooleanField(default=True)),
                ('skipped', models.BooleanField(default=False)),
                ('sample_time', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='models_manager.datasetevaluationresult')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='datasetevaluationresult',
            index=models.Index(fields=['dataset_name'], name='models_mana_dataset_d_f40b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationresult',
            index=models.Index(fields=['model_name'], name='models_mana_model_na_ab0eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationresult',
            index=models.Index(fields=['status'], name='models_mana_status_1d72cd_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationresult',
            index=models.Index(fields=['created_at'], name='models_mana_created__fb2a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationsample',
            index=models.Index(fields=['result', 'index'], name='models_mana_result_i_19b27f_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationsample',
            index=models.Index(fields=['result', 'is_correct'], name='models_mana_result_i_d27180_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetevaluationsample',
            index=models.Index(fields=['result', 'skipped'], name='models_mana_result_s_6a361c_idx'),
        ),
    ]
