# Generated by Django 5.1 on 2025-12-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0, help_text='综合总分')),
                ('scores', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_score', to='models_manager.aimodel')),
            ],
        ),
    ]
