# Generated by Django 5.1 on 2025-11-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0002_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='model_name',
            field=models.CharField(blank=True, help_text='对话使用的模型名称', max_length=100, null=True),
        ),
    ]
