# Generated by Django 5.1 on 2025-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0003_chatconversation_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='mode',
            field=models.CharField(choices=[('direct-chat', 'Direct Chat'), ('side-by-side', 'Side by Side'), ('battle', 'Battle')], default='direct-chat', help_text='对话模式', max_length=20),
        ),
    ]
