# Generated by Django 5.1 on 2025-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0004_chatconversation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model_name',
            field=models.CharField(blank=True, help_text='生成此消息的模型名称（仅AI消息）', max_length=100, null=True),
        ),
    ]
