# Generated by Django 5.1 on 2025-11-18 03:35

from django.db import migrations
from django.utils.text import slugify


def seed_defaults(apps, schema_editor):
    Category = apps.get_model('forum', 'ForumCategory')
    Tag = apps.get_model('forum', 'ForumTag')

    categories = [
        '技术交流',
        '功能建议',
        '作品分享',
        '问题反馈',
        '公告与更新',
    ]

    for index, name in enumerate(categories):
        slug = slugify(name) or f'category-{index}'
        Category.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'sort_order': index,
                'is_active': True,
            },
        )

    tags = ['讨论', '建议', '问题', '作品', '公告']
    for tag_name in tags:
        slug = slugify(tag_name) or tag_name
        Tag.objects.get_or_create(slug=slug, defaults={'name': tag_name})


def unseed_defaults(apps, schema_editor):
    Category = apps.get_model('forum', 'ForumCategory')
    Tag = apps.get_model('forum', 'ForumTag')

    category_slugs = [slugify(name) or f'category-{idx}' for idx, name in enumerate([
        '技术交流',
        '功能建议',
        '作品分享',
        '问题反馈',
        '公告与更新',
    ])]
    tag_slugs = [slugify(name) or name for name in ['讨论', '建议', '问题', '作品', '公告']]

    Category.objects.filter(slug__in=category_slugs).delete()
    Tag.objects.filter(slug__in=tag_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_defaults, reverse_code=unseed_defaults),
    ]
