# Generated by Django 5.1 on 2025-11-26 10:18

import django.db.models.deletion
import forum.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsharelog',
            name='post',
        ),
        migrations.RemoveField(
            model_name='forumsharelog',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='forumattachment',
            options={'ordering': ('-created_at',), 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='views',
        ),
        migrations.AlterField(
            model_name='forumattachment',
            name='file',
            field=models.ImageField(upload_to=forum.models.forum_attachment_upload_to),
        ),
        migrations.CreateModel(
            name='ForumPostFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favorites', to='forum.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to='forum.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_view_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ForumPostLike',
        ),
        migrations.DeleteModel(
            name='ForumShareLog',
        ),
        migrations.AddIndex(
            model_name='forumpostfavorite',
            index=models.Index(fields=['user', 'post'], name='forum_forum_user_id_c629cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumpostfavorite',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='forumpostviewhistory',
            index=models.Index(fields=['user', 'last_viewed_at'], name='forum_forum_user_id_725e5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumpostviewhistory',
            unique_together={('post', 'user')},
        ),
    ]
