# Generated by Django 5.1 on 2025-12-02 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumattachment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.forumcomment'),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.forumcomment'),
        ),
        migrations.AddField(
            model_name='forumcommentimage',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.forumcomment'),
        ),
        migrations.AddField(
            model_name='forumcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='forum.forumcomment'),
        ),
        migrations.AddField(
            model_name='forumcommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumcommentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.forumcomment'),
        ),
        migrations.AddField(
            model_name='forumcommentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='forum.forumcategory'),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpostfavorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favorites', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpostfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpostreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpostreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpostviewhistory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpostviewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_view_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='forum.forumtag'),
        ),
        migrations.AlterUniqueTogether(
            name='forumcommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='forumcommentreaction',
            unique_together={('comment', 'user', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='forumpostfavorite',
            index=models.Index(fields=['user', 'post'], name='forum_forum_user_id_c629cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumpostfavorite',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='forumpostreaction',
            unique_together={('post', 'user', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='forumpostviewhistory',
            index=models.Index(fields=['user', 'last_viewed_at'], name='forum_forum_user_id_725e5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumpostviewhistory',
            unique_together={('post', 'user')},
        ),
    ]
