# Generated by Django 5.1 on 2025-11-26 10:18

import django.db.models.deletion
import forum.models
from django.conf import settings
from django.db import migrations, models


def check_table_exists(schema_editor, table_name):
    """检查表是否存在"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = %s
        """, [table_name])
        return cursor.fetchone()[0] > 0


def safe_remove_forumsharelog_fields(apps, schema_editor):
    """安全地删除 ForumShareLog 字段"""
    if check_table_exists(schema_editor, 'forum_forumsharelog'):
        # 表存在才执行删除操作
        ForumShareLog = apps.get_model('forum', 'ForumShareLog')
        # Django 会自动处理字段删除
        pass


def reverse_safe_remove(apps, schema_editor):
    """反向迁移占位符"""
    pass


def safe_remove_views_field(apps, schema_editor):
    """安全地删除 views 字段"""
    with schema_editor.connection.cursor() as cursor:
        # 检查字段是否存在
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'forum_forumpost'
            AND column_name = 'views'
        """)
        if cursor.fetchone()[0] > 0:
            # 字段存在才删除
            cursor.execute("ALTER TABLE `forum_forumpost` DROP COLUMN `views`")


def reverse_safe_remove_views(apps, schema_editor):
    """反向迁移占位符"""
    pass


def safe_delete_models(apps, schema_editor):
    """安全地删除模型表"""
    tables_to_delete = [
        ('forum_forumpostlike', 'ForumPostLike'),
        ('forum_forumsharelog', 'ForumShareLog')
    ]
    
    for table_name, model_name in tables_to_delete:
        if check_table_exists(schema_editor, table_name):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(f"DROP TABLE IF EXISTS `{table_name}`")


def reverse_safe_delete(apps, schema_editor):
    """反向迁移占位符"""
    pass


def safe_create_models(apps, schema_editor):
    """安全地创建模型表 - 如果不存在才创建"""
    # 检查表是否已存在,如果存在就跳过创建
    if not check_table_exists(schema_editor, 'forum_forumpostfavorite'):
        # 表不存在,创建它
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE `forum_forumpostfavorite` (
                    `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                    `created_at` datetime(6) NOT NULL,
                    `post_id` bigint NOT NULL,
                    `user_id` bigint NOT NULL,
                    UNIQUE (`post_id`, `user_id`),
                    CONSTRAINT `forum_forumpostfavorite_post_id` 
                        FOREIGN KEY (`post_id`) REFERENCES `forum_forumpost` (`id`),
                    CONSTRAINT `forum_forumpostfavorite_user_id` 
                        FOREIGN KEY (`user_id`) REFERENCES `users_user` (`id`)
                )
            """)
            # 添加索引
            cursor.execute("""
                CREATE INDEX `forum_forum_user_id_c629cb_idx` 
                ON `forum_forumpostfavorite` (`user_id`, `post_id`)
            """)
    
    if not check_table_exists(schema_editor, 'forum_forumpostviewhistory'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE `forum_forumpostviewhistory` (
                    `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                    `view_count` int UNSIGNED NOT NULL,
                    `last_viewed_at` datetime(6) NOT NULL,
                    `post_id` bigint NOT NULL,
                    `user_id` bigint NOT NULL,
                    UNIQUE (`post_id`, `user_id`),
                    CONSTRAINT `forum_forumpostviewhistory_post_id` 
                        FOREIGN KEY (`post_id`) REFERENCES `forum_forumpost` (`id`),
                    CONSTRAINT `forum_forumpostviewhistory_user_id` 
                        FOREIGN KEY (`user_id`) REFERENCES `users_user` (`id`)
                )
            """)
            # 添加索引
            cursor.execute("""
                CREATE INDEX `forum_forum_user_id_725e5f_idx` 
                ON `forum_forumpostviewhistory` (`user_id`, `last_viewed_at`)
            """)


def reverse_safe_create(apps, schema_editor):
    """反向迁移占位符"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 使用自定义函数检查表是否存在
        migrations.RunPython(safe_remove_forumsharelog_fields, reverse_safe_remove),
        migrations.AlterModelOptions(
            name='forumattachment',
            options={'ordering': ('-created_at',), 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        # 使用自定义函数安全删除 views 字段
        migrations.RunPython(safe_remove_views_field, reverse_safe_remove_views),
        migrations.AlterField(
            model_name='forumattachment',
            name='file',
            field=models.ImageField(upload_to=forum.models.forum_attachment_upload_to),
        ),
        # 使用自定义函数安全创建模型(如果不存在才创建)
        migrations.RunPython(safe_create_models, reverse_safe_create),
        # 使用自定义函数安全删除表
        migrations.RunPython(safe_delete_models, reverse_safe_delete),
    ]
