# Generated by Django 5.1 on 2025-12-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forumsharelog_post_remove_forumsharelog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPostFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='forumpostlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='forumpostlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='forumpostlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumsharelog',
            name='post',
        ),
        migrations.RemoveField(
            model_name='forumsharelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='views',
        ),
        migrations.AddIndex(
            model_name='forumcomment',
            index=models.Index(fields=['post_id', '-created_at'], name='forum_forum_post_id_6c01d5_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcomment',
            index=models.Index(fields=['author_id', '-created_at'], name='forum_forum_author__a7f621_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcomment',
            index=models.Index(fields=['parent_id', 'created_at'], name='forum_forum_parent__d6e82c_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcommentlike',
            index=models.Index(fields=['comment_id', '-created_at'], name='forum_forum_comment_05d79f_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcommentlike',
            index=models.Index(fields=['user_id', '-created_at'], name='forum_forum_user_id_75fe02_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcommentreaction',
            index=models.Index(fields=['comment_id', '-created_at'], name='forum_forum_comment_113dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcommentreaction',
            index=models.Index(fields=['user_id', '-created_at'], name='forum_forum_user_id_e0d89b_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author_id', '-created_at'], name='forum_forum_author__e19f06_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['category_obj_id', '-created_at'], name='forum_forum_categor_63e4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['-last_activity_at'], name='forum_forum_last_ac_2c729a_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['status', '-created_at'], name='forum_forum_status_14ff61_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['is_sticky', '-created_at'], name='forum_forum_is_stic_61d212_idx'),
        ),
        migrations.AddField(
            model_name='forumpostfavorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favorites', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpostfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpostviewhistory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpostviewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_view_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ForumPostLike',
        ),
        migrations.DeleteModel(
            name='ForumShareLog',
        ),
        migrations.AddIndex(
            model_name='forumpostfavorite',
            index=models.Index(fields=['user', 'post'], name='forum_forum_user_id_c629cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumpostfavorite',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='forumpostviewhistory',
            index=models.Index(fields=['user', 'last_viewed_at'], name='forum_forum_user_id_725e5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumpostviewhistory',
            unique_together={('post', 'user')},
        ),
    ]
