# Generated by Django 5.1 on 2025-11-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumcommentimage'),
        ('forum', '0003_forumattachment'),
    ]

    operations = [
    ]
