# Generated by Django 5.1 on 2025-11-25 07:57

from django.db import migrations


def _drop_views_if_exists(apps, schema_editor):
    """Drop the `views` column from forum_forumpost if it exists (safe for merged branches)."""
    table = "forum_forumpost"
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME='views'",
            [table],
        )
        exists = cursor.fetchone()[0]
        if exists:
            cursor.execute(f"ALTER TABLE `{table}` DROP COLUMN `views`")


def _drop_forumsharelog_fields_if_exists(apps, schema_editor):
    table = "forum_forumsharelog"
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        for col in ("post_id", "user_id"):
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s",
                [table, col],
            )
            if cursor.fetchone()[0]:
                cursor.execute(f"ALTER TABLE `{table}` DROP COLUMN `{col}`")


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_merge_0002_forumcommentimage_0003_forumattachment'),
    ]

    operations = [
        # Safely drop forumsharelog.post and forumsharelog.user columns if present
        migrations.RunPython(_drop_forumsharelog_fields_if_exists, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='forumcommentimage',
            options={'ordering': ('-uploaded_at',)},
        ),
        # Use RunPython to safely drop the `views` column only if it exists.
        migrations.RunPython(_drop_views_if_exists, reverse_code=migrations.RunPython.noop),
        # Drop legacy tables if they exist (safe for merged histories)
        migrations.RunSQL("DROP TABLE IF EXISTS `forum_forumpostlike`", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL("DROP TABLE IF EXISTS `forum_forumsharelog`", reverse_sql=migrations.RunSQL.noop),
    ]
