# Generated by Django 5.1 on 2025-11-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_forumsharelog_post_remove_forumsharelog_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsharelog',
            name='post',
        ),
        migrations.RemoveField(
            model_name='forumsharelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='views',
        ),
        migrations.DeleteModel(
            name='ForumPostLike',
        ),
        migrations.DeleteModel(
            name='ForumShareLog',
        ),
    ]
