# Generated by Django 5.1 on 2025-11-26 03:22

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = []
