# Generated by Django 5.1 on 2025-12-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forumpostshare'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='forumpostshare',
            new_name='forum_forum_sender__6541fb_idx',
            old_name='forum_forump_sender_4cc608_idx',
        ),
        migrations.RenameIndex(
            model_name='forumpostshare',
            new_name='forum_forum_receive_fee72a_idx',
            old_name='forum_forump_receiver_8265d4_idx',
        ),
    ]
