# Generated by Django 5.1 on 2025-11-19 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # 调整依赖：移除对 forum 0002 的依赖，改为依赖 forum 初始迁移，避免在开发环境缺失 0002 时阻塞。
    # Notification 仅使用 ForumPost/ForumComment，不需要 ForumCommentImage。
    dependencies = [
        ('forum', '0001_initial'),
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.ImageField(blank=True, help_text='上传头像文件', null=True, upload_to='users/avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='外部头像URL（兼容旧数据）'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('post_like', '帖子被点赞'), ('post_comment', '帖子收到评论'), ('comment_reply', '评论被回复'), ('comment_like', '评论被点赞')], max_length=32)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forumcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='users_notif_recipie_2469dd_idx'), models.Index(fields=['action_type'], name='users_notif_action__57f5d9_idx')],
            },
        ),
    ]
