# Generated by Django 5.1 on 2025-11-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_file_alter_user_avatar_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='外部头像URL（优先使用该字段）'),
        ),
    ]
