# Generated by Django 5.1 on 2025-11-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, help_text='微信OpenID', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_unionid',
            field=models.CharField(blank=True, help_text='微信UnionID', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='外部头像URL(优先使用该字段)'),
        ),
    ]
