# Generated by Django 5.1 on 2025-11-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_wechat_openid_user_wechat_unionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('post_like', '帖子被点赞'), ('post_comment', '帖子收到评论'), ('comment_reply', '评论被回复'), ('comment_like', '评论被点赞'), ('post_favorite', '帖子被收藏')], max_length=32),
        ),
    ]
