# Generated by Django 5.1 on 2025-12-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_notification_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_threads_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_threads_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user_a', 'updated_at'], name='users_privat_user_a_2809ec_idx'),
                    models.Index(fields=['user_b', 'updated_at'], name='users_privat_user_b_ae4dd7_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['follower'], name='users_userfo_followe_f9a8b8_idx'),
                    models.Index(fields=['following'], name='users_userfo_followi_592a2a_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_private_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.privatechatthread')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['thread', 'created_at'], name='users_privatem_thread_0a02c7_idx'),
                    models.Index(fields=['thread', 'is_read'], name='users_privatem_thread_c1e91b_idx'),
                ],
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='privatechatthread',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_private_chat_pair'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow_relation'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(check=~models.Q(follower=models.F('following')), name='prevent_self_follow'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('post_like', '帖子被点赞'), ('post_comment', '帖子收到评论'), ('comment_reply', '评论被回复'), ('comment_like', '评论被点赞'), ('post_favorite', '帖子被收藏'), ('follow', '获得新关注'), ('mutual_follow', '互相关注'), ('post_share', '帖子被分享'), ('private_message', '收到私聊消息')], max_length=32),
        ),
    ]
