# Generated by Django 5.1 on 2025-12-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userfollow_privatechat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='privatechatthread',
            new_name='users_priva_user_a__0e15e9_idx',
            old_name='users_privat_user_a_2809ec_idx',
        ),
        migrations.RenameIndex(
            model_name='privatechatthread',
            new_name='users_priva_user_b__1970ef_idx',
            old_name='users_privat_user_b_ae4dd7_idx',
        ),
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='users_priva_thread__151077_idx',
            old_name='users_privatem_thread_0a02c7_idx',
        ),
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='users_priva_thread__4e4460_idx',
            old_name='users_privatem_thread_c1e91b_idx',
        ),
        migrations.RenameIndex(
            model_name='userfollow',
            new_name='users_userf_followe_2b72fd_idx',
            old_name='users_userfo_followe_f9a8b8_idx',
        ),
        migrations.RenameIndex(
            model_name='userfollow',
            new_name='users_userf_followi_fd7511_idx',
            old_name='users_userfo_followi_592a2a_idx',
        ),
    ]
