# Generated by Django 5.1 on 2025-12-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
        ('users', '0008_rename_users_privat_user_a_2809ec_idx_users_priva_user_a__0e15e9_idx_and_more'),
    ]

    operations = [
    ]
